package atinternet

type Metrics []Metric

type Metric string

func (metrics Metrics) String() []string {

	metricsString := []string{}

	for _, metric := range metrics {
		metricsString = append(metricsString, string(metric))
	}

	return metricsString
}

const (
	MAbortFunnel                  Metric = "m_abort_funnel"
	MAbortStep                    Metric = "m_abort_step"
	MAdvImpressions               Metric = "m_adv_impressions"
	MAisleLoads                   Metric = "m_aisle_loads"
	MBounceRate                   Metric = "m_bounce_rate"
	MBounces                      Metric = "m_bounces"
	MBq                           Metric = "m_bq"
	MClicks                       Metric = "m_clicks"
	MConv1VisitsContribution      Metric = "m_conv1_visits_contribution"
	MConv2VisitsContribution      Metric = "m_conv2_visits_contribution"
	MConversionFunnel             Metric = "m_conversion_funnel"
	MConversions1Loads            Metric = "m_conversions1_loads"
	MConversions1Rate             Metric = "m_conversions1_rate"
	MConversions1Visits           Metric = "m_conversions1_visits"
	MConversions1VisitsPa         Metric = "m_conversions1_visits_pa"
	MConversions1VisitsRevised    Metric = "m_conversions1_visits_revised"
	MConversions2Loads            Metric = "m_conversions2_loads"
	MConversions2Visits           Metric = "m_conversions2_visits"
	MConversionStep               Metric = "m_conversion_step"
	MCtsLoads                     Metric = "m_cts_loads"
	MCustomers                    Metric = "m_customers"
	MCzClicks                     Metric = "m_cz_clicks"
	MCzTime                       Metric = "m_cz_time"
	MDays                         Metric = "m_days"
	MDiscountTaxFree              Metric = "m_discount_tax_free"
	MDiscountWithTax              Metric = "m_discount_with_tax"
	MEmailOpens                   Metric = "m_email_opens"
	MEnteringVisits               Metric = "m_entering_visits"
	MEntryRate                    Metric = "m_entry_rate"
	MIseClicks                    Metric = "m_ise_clicks"
	MIseExitRate                  Metric = "m_ise_exit_rate"
	MIseExitVisits                Metric = "m_ise_exit_visits"
	MIsePageViews                 Metric = "m_ise_page_views"
	MLatencyPeriodPa              Metric = "m_latency_period_pa"
	MNbFirstOrders                Metric = "m_nb_first_orders"
	MNbOrders                     Metric = "m_nb_orders"
	MPageLoads                    Metric = "m_page_loads"
	MPageLoadsPerVisits           Metric = "m_page_loads_per_visits"
	MPageViews                    Metric = "m_page_views"
	MPageViewsPerEnteringVisits   Metric = "m_page_views_per_entering_visits"
	MPageViewsPerVisits           Metric = "m_page_views_per_visits"
	MPodcastLoads                 Metric = "m_podcast_loads"
	MProductAbandonedQuantity     Metric = "m_product_abandoned_quantity"
	MProductAbandonedSalesTaxFree Metric = "m_product_abandoned_sales_tax_free"
	MProductAbandonedSalesWithTax Metric = "m_product_abandoned_sales_with_tax"
	MProductAbandonRate           Metric = "m_product_abandon_rate"
	MProductBasketAbandonRate     Metric = "m_product_basket_abandon_rate"
	MProductBoughtQuantity        Metric = "m_product_bought_quantity"
	MProductDiscountTaxFree       Metric = "m_product_discount_tax_free"
	MProductDiscountWithTax       Metric = "m_product_discount_with_tax"
	MProductLoads                 Metric = "m_product_loads"
	MProductNbAbandonedBaskets    Metric = "m_product_nb_abandoned_baskets"
	MProductNbOrders              Metric = "m_product_nb_orders"
	MProductSalesTaxFree          Metric = "m_product_sales_tax_free"
	MProductSalesWithTax          Metric = "m_product_sales_with_tax"
	MPubClickRate                 Metric = "m_pub_click_rate"
	MPubClicks                    Metric = "m_pub_clicks"
	MPubImpressions               Metric = "m_pub_impressions"
	MRmBuffer                     Metric = "m_rm_buffer"
	MRmDownload                   Metric = "m_rm_download"
	MRmEmail                      Metric = "m_rm_email"
	MRmFavorite                   Metric = "m_rm_favorite"
	MRmFullplaybacks              Metric = "m_rm_fullplaybacks"
	MRmFullplaybacksRate          Metric = "m_rm_fullplaybacks_rate"
	MRmInteractions               Metric = "m_rm_interactions"
	MRmMove                       Metric = "m_rm_move"
	MRmPause                      Metric = "m_rm_pause"
	MRmPlay                       Metric = "m_rm_play"
	MRmPlaybackBuffer             Metric = "m_rm_playback_buffer"
	MRmPlaybackMove               Metric = "m_rm_playback_move"
	MRmPlaybackProgressRate       Metric = "m_rm_playback_progress_rate"
	MRmPlaybackTimePlaycount      Metric = "m_rm_playback_time_playcount"
	MRmPlaycounts                 Metric = "m_rm_playcounts"
	MRmShare                      Metric = "m_rm_share"
	MRmStop                       Metric = "m_rm_stop"
	MRmTimeSpent                  Metric = "m_rm_time_spent"
	MRmTimeSpentBuffer            Metric = "m_rm_time_spent_buffer"
	MRssLoads                     Metric = "m_rss_loads"
	MSales                        Metric = "m_sales"
	MSalesContribution            Metric = "m_sales_contribution"
	MSalesPerOrders               Metric = "m_sales_per_orders"
	MSalesTaxFree                 Metric = "m_sales_tax_free"
	MSalesWithTax                 Metric = "m_sales_with_tax"
	MShippingFeesTaxFree          Metric = "m_shipping_fees_tax_free"
	MShippingFeesWithTax          Metric = "m_shipping_fees_with_tax"
	MSourceClicks                 Metric = "m_source_clicks"
	MSpClickRate                  Metric = "m_sp_click_rate"
	MSpClicks                     Metric = "m_sp_clicks"
	MSpImpressions                Metric = "m_sp_impressions"
	MSurveyAnswerLoads            Metric = "m_survey_answer_loads"
	MSurveyLoads                  Metric = "m_survey_loads"
	MSurveyQuestionLoads          Metric = "m_survey_question_loads"
	MTax                          Metric = "m_tax"
	MTimeSpent                    Metric = "m_time_spent"
	MTimeSpentBufferingRead       Metric = "m_time_spent_buffering_read"
	MTimeSpentPerConvFunnel       Metric = "m_time_spent_per_conv_funnel"
	MTimeSpentPerFunnel           Metric = "m_time_spent_per_funnel"
	MTimeSpentPerPages            Metric = "m_time_spent_per_pages"
	MTimeSpentPerPagesLoads       Metric = "m_time_spent_per_pages_loads"
	MTimeSpentPerPagesVisits      Metric = "m_time_spent_per_pages_visits"
	MTimeSpentPerVisits           Metric = "m_time_spent_per_visits"
	MVisitors                     Metric = "m_visitors"
	MVisitorsPage                 Metric = "m_visitors_page"
	MVisits                       Metric = "m_visits"
	MVisitsAll                    Metric = "m_visits_all"
	MVisitsNopages                Metric = "m_visits_nopages"
	MVisitsPa                     Metric = "m_visits_pa"
	MVRevisedSales                Metric = "m_v_revised_sales"
	MVRevisedSalesPa              Metric = "m_v_revised_sales_pa"
	MVSales                       Metric = "m_v_sales"
	MVSalesPa                     Metric = "m_v_sales_pa"
	MVSalesPerConversions1        Metric = "m_v_sales_per_conversions1"
	MUniqueVisitors               Metric = "m_unique_visitors"
	MAppNewVisitors               Metric = "m_app_newvisitors"
	MAppReturnV                   Metric = "m_app_returnv"
	M2UniqueVisitors              Metric = "m_uv"
)
